desicion = input("Desea 'traducir' o 'codificar' el mensaje?")
if desicion.lower() == "traducir":
    palabra = input("Ingrese la palabra a traducir: ")
    palabragod = palabra.lower()
    palabragod = palabragod.replace("@","a")
    palabragod = palabragod.replace("#","e")
    palabragod = palabragod.replace("&","i")
    palabragod = palabragod.replace("$","o")
    palabragod = palabragod.replace("*","u")
    print(palabragod)
if desicion.lower() == "codificar":
    palabra = input("Ingrese la palabra a codificar: ")
    palabragod = palabra.lower()
    palabragod = palabragod.replace("a","@")
    palabragod = palabragod.replace("e","#")
    palabragod = palabragod.replace("i","&")
    palabragod = palabragod.replace("o","$")
    palabragod = palabragod.replace("u","*")
    print(palabragod)
    